"""
HumanEval Infilling eval -- the metric Mellum's own model card reports.

Mellum-4b-base reports (as of April 2026 model card):
  Single-Line: 0.6621
  Multi-Line:  0.3852
  Random Span: 0.2970

Bavarian et al. 2022 introduced the dataset; loubnabnl/humaneval_infilling
on HF mirrors it. Three configs (SingleLine 1033 / MultiLine 5815 /
RandomSpan 1640 examples). Each example gives prefix + suffix; the model
infills the middle. pass@1 is computed by running the original test against
the reconstructed solution.

Notes on this script:

  - I sub-sample each config to keep modal compute under budget. Running
    the full 8488 problems × 5 models would be ~12h on A10G; 164 problems
    per config keeps it under an hour while still giving a defensible
    sample size with the caveats stated in the report. (164 matches the
    HumanEval prompt count used in spec_eval.py for symmetry.)

  - Need datasets==3.6.0 with trust_remote_code=True because the dataset
    uses a loader script that newer datasets versions deprecated.

  - Mellum uses its own FIM tokens (<fim_prefix>, <fim_suffix>,
    <fim_middle> in SPM order); Qwen2.5-Coder uses <|fim_prefix|>,
    <|fim_suffix|>, <|fim_middle|> in PSM order. Both models are
    FIM-pretrained so the embeddings are warm. The script picks the right
    template per model.
"""

from __future__ import annotations
from pathlib import Path
import argparse
import json
import os
import subprocess
import sys
import tempfile
import time
import torch
from datasets import load_dataset
from transformers import AutoModelForCausalLM, AutoTokenizer

from fim_train import get_qwen_fim_tokens


SUBSETS = {
    "single_line": "HumanEval-SingleLineInfilling",
    "multi_line":  "HumanEval-MultiLineInfilling",
    "random_span": "HumanEval-RandomSpanInfilling",
}


def build_qwen_fim(prefix: str, suffix: str, tok, fim) -> torch.Tensor:
    pre_ids = tok(prefix, add_special_tokens=False).input_ids
    suf_ids = tok(suffix, add_special_tokens=False).input_ids
    ids = (
        [fim.prefix] + pre_ids
        + [fim.suffix] + suf_ids
        + [fim.middle]
    )
    return torch.tensor([ids], dtype=torch.long)


def build_mellum_fim(prefix: str, suffix: str, tok) -> torch.Tensor:
    prompt = f"<fim_suffix>{suffix}<fim_prefix>{prefix}<fim_middle>"
    return tok(prompt, return_tensors="pt").input_ids


def truncate_completion(text: str) -> str:
    """Cut at the first sign the model has finished the infill."""
    for stop in ["<|endoftext|>", "<|fim_pad|>", "<fim_pad>", "<file_sep>", "<filename>"]:
        idx = text.find(stop)
        if idx != -1:
            text = text[:idx]
    return text


def run_test(prefix: str, completion: str, suffix: str, test: str, entry: str) -> bool:
    """Same isolation note as eval.run_one_humaneval: -I + tempdir cwd +
    fixed hash seed. Untrusted code generated by a small model, but it's
    plain function bodies, not attempted exploits."""
    program = prefix + completion + suffix + "\n" + test + f"\ncheck({entry})\n"
    with tempfile.TemporaryDirectory() as td:
        env = {**os.environ, "PYTHONHASHSEED": "0"}
        try:
            out = subprocess.run(
                [sys.executable, "-I", "-c", program],
                capture_output=True,
                timeout=10,
                text=True,
                cwd=td,
                env=env,
            )
        except subprocess.TimeoutExpired:
            return False
    return out.returncode == 0


@torch.no_grad()
def eval_subset(
    name: str,
    model,
    tok,
    fim,
    is_mellum: bool,
    subset_key: str,
    n_problems: int,
    max_new: int,
    device,
    seed: int,
) -> dict:
    config_name = SUBSETS[subset_key]
    ds = load_dataset("loubnabnl/humaneval_infilling", config_name, split="test", trust_remote_code=True)
    # deterministic subsample by seed for cross-model comparability
    import random
    rng = random.Random(seed)
    indices = list(range(len(ds)))
    rng.shuffle(indices)
    indices = indices[:n_problems]
    ds = ds.select(indices)

    n_pass = 0
    rows: list[dict] = []
    t0 = time.time()
    for ex in ds:
        prefix = ex["prompt"]
        suffix = ex["suffix"]
        if is_mellum:
            ids = build_mellum_fim(prefix, suffix, tok).to(device)
        else:
            ids = build_qwen_fim(prefix, suffix, tok, fim).to(device)
        out = model.generate(
            ids,
            max_new_tokens=max_new,
            do_sample=False,
            pad_token_id=tok.eos_token_id,
            eos_token_id=tok.eos_token_id,
        )
        gen = tok.decode(out[0, ids.size(1) :], skip_special_tokens=True)
        gen = truncate_completion(gen)
        passed = run_test(prefix, gen, suffix, ex["test"], ex["entry_point"])
        n_pass += int(passed)
        rows.append({"task_id": ex["task_id"], "passed": passed, "completion": gen[:200]})
    elapsed = time.time() - t0
    return {
        "subset": subset_key,
        "config": config_name,
        "n": len(rows),
        "pass@1": n_pass / max(len(rows), 1),
        "elapsed_s": elapsed,
        "per_problem": rows,
    }


def evaluate(
    name: str, path: str, n_problems: int, max_new: int,
    base_tok_path: str, device, seed: int,
) -> dict:
    is_mellum = "mellum" in name.lower() and "fim_mellum" not in name.lower()
    if is_mellum:
        tok = AutoTokenizer.from_pretrained(path)
        fim = None
    else:
        tok = AutoTokenizer.from_pretrained(base_tok_path)
        fim = get_qwen_fim_tokens(tok)
    model = AutoModelForCausalLM.from_pretrained(path, dtype=torch.bfloat16).to(device)
    model.eval()
    print(f"\n=== {name} ({path}) ===")
    out = {"name": name, "ckpt": path, "subsets": {}}
    for subset_key in SUBSETS:
        r = eval_subset(name, model, tok, fim, is_mellum, subset_key, n_problems, max_new, device, seed)
        out["subsets"][subset_key] = r
        print(f"  {subset_key}: pass@1 = {r['pass@1']:.3f}  (n={r['n']}, {r['elapsed_s']:.0f}s)")
    overall = sum(out["subsets"][s]["pass@1"] for s in SUBSETS) / 3
    out["mean_pass@1"] = overall
    print(f"  mean pass@1: {overall:.3f}")
    del model
    torch.cuda.empty_cache()
    return out


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--student-base", default="/home/prannayk/models/qwen-coder-0.5b")
    ap.add_argument("--ckpt-dir", type=Path, default=Path("checkpoints"))
    ap.add_argument("--mellum", default="/home/prannayk/models/mellum-sft-python")
    ap.add_argument("--out", type=Path, default=Path("results/humaneval_infilling.json"))
    ap.add_argument("--n-problems", type=int, default=100,
                    help="problems per subset; full set is 1033/5815/1640 -- defaults to a 100-per-subset subsample with a fixed seed")
    ap.add_argument("--max-new", type=int, default=128)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    device = torch.device("cuda")
    runs = [
        ("base",        args.student_base),
        ("fim_gold",    str(args.ckpt_dir / "student_fim_gold")),
        ("fim_mellum",  str(args.ckpt_dir / "student_fim_mellum")),
        ("fim_mix",     str(args.ckpt_dir / "student_fim_mix")),
        ("mellum_4b",   args.mellum),
    ]
    out: dict = {"args": {"n_problems_per_subset": args.n_problems, "max_new": args.max_new, "seed": args.seed}}
    for name, path in runs:
        if not Path(path).exists():
            print(f"missing {path}, skip")
            continue
        out[name] = evaluate(name, path, args.n_problems, args.max_new, args.student_base, device, args.seed)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(out, indent=2))
    print(f"\nwrote {args.out}")


if __name__ == "__main__":
    main()
